In [9]:
import scipy.io as sio
import numpy as np

In [11]:
data = sio.loadmat("/Users/HZzone/Desktop/Stanford-Cars-Classification/data/cars_meta.mat")
data = data["class_names"]
print(data.shape)

(1, 196)


In [15]:
data = sio.loadmat("/Users/HZzone/Desktop/Stanford-Cars-Classification/data/cars_train_annos.mat")
data = data["annotations"]
print(data.shape)
print(data)

(1, 8144)
[[ (array([[39]], dtype=uint8), array([[116]], dtype=uint8), array([[569]], dtype=uint16), array([[375]], dtype=uint16), array([[14]], dtype=uint8), array(['00001.jpg'], 
      dtype='<U9'))
  (array([[36]], dtype=uint8), array([[116]], dtype=uint8), array([[868]], dtype=uint16), array([[587]], dtype=uint16), array([[3]], dtype=uint8), array(['00002.jpg'], 
      dtype='<U9'))
  (array([[85]], dtype=uint8), array([[109]], dtype=uint8), array([[601]], dtype=uint16), array([[381]], dtype=uint16), array([[91]], dtype=uint8), array(['00003.jpg'], 
      dtype='<U9'))
  ...,
  (array([[26]], dtype=uint8), array([[246]], dtype=uint8), array([[660]], dtype=uint16), array([[449]], dtype=uint16), array([[163]], dtype=uint8), array(['08142.jpg'], 
      dtype='<U9'))
  (array([[78]], dtype=uint8), array([[526]], dtype=uint16), array([[1489]], dtype=uint16), array([[908]], dtype=uint16), array([[112]], dtype=uint8), array(['08143.jpg'], 
      dtype='<U9'))
  (array([[20]], dtype=uint8)